// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqfmcksbacfkwokmgqtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxZm1ja3NiYWNma3dva21ncXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIwNTM5MDgsImV4cCI6MjA5NzYyOTkwOH0.lrmG0eHkBFjvskw19_h2TQND2K649lbCRICZcbOtWts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});